name: api_usage_example
description: "restcountries.com showcase"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  dio: ^5.7.0
  retrofit: ^4.4.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  auto_route: ^9.2.2
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5
  riverpod_generator: ^2.6.3
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
